# Docker Compose Configuration for PostgreSQL, Redis, and Microservices

services:
  # PostgreSQL container (slimmed down)
  PostgresContainer:
    container_name: smartbus-prod-PostgresContainer
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12683579
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  # Auth service (prod)
  auth-prod:
    container_name: smartbus-prod-Auth
    build:
      context: ./Auth
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgresContainer:5432/AuthDBProd
    ports:
      - "10000:10000"
    depends_on:
      - PostgresContainer

  # Feedback service (prod)
  feedback-prod:
    container_name: smartbus-prod-Feedback
    build:
      context: ./Feedback
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgresContainer:5432/FeedbackDBProd
    ports:
      - "10050:10050"
    depends_on:
      - PostgresContainer

  # GTFS service
  gtfs:
    container_name: smartbus-prod-GTFS
    build:
      context: ./GTFS
      dockerfile: Dockerfile
      args:
        PROFILE: prod
    volumes:
      - ./GTFS/prod/public:/app/GtfsScript/public # Mounting public folder for GTFS data
      - type: bind
        source: ./GTFS/prod/config.yaml
        target: /app/GtfsScript/config/config.yaml
    depends_on:
      - PostgresContainer
    environment:
      - POSTGRES_URL=jdbc:postgresql://PostgresContainer:5432/GTFSProd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12683579
    ports:
      - "9000:9000" # Or the port you need to expose for GTFS

  # OrderBus service (prod)
  orderbus-prod:
    container_name: smartbus-prod-OrderBus
    build:
      context: ./OrderBus
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgresContainer:5432/gtfs
    ports:
      - "10093:10093"
    depends_on:
      - PostgresContainer
      - gtfs
      - routes-prod
      - RedisContainer

  # Routes service (prod)
  routes-prod:
    container_name: smartbus-prod-Routes
    build:
      context: ./Routes
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "10094:10094"

  # Redis container (slimmed down)
  RedisContainer:
    container_name: smartbus-prod-RedisContainer
    image: redis:7-alpine
    ports:
      - "6379:6379" # Redis default port
    volumes:
      - redis-data-prod:/data


  # Add the Nginx service for production
  nginx:
    container_name: smartbus-prod-nginx
    image: nginx:latest
    ports:
      - "8080:8080" # Exposing port 8080
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/nginx.conf # Mounting prod configuration
    depends_on:
      - auth-prod
      - feedback-prod
      - gtfs
      - orderbus-prod
      - routes-prod
    networks:
      - smartbus-net


volumes:
  postgres-data-prod:
  redis-data-prod:
