# Docker Compose Configuration for PostgreSQL, Redis, and Microservices (Development Environment)

services:
  # PostgresSQL container (development)
  PostgresContainer:
    container_name: smartbus-dev-PostgresContainer
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12683579
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - smartbus-net

  # Auth service (dev)
  auth-dev:
    container_name: smartbus-dev-Auth
    build:
      context: ./Auth
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgresContainer:5432/AuthDBDev
    ports:
      - "3804:3804"
    depends_on:
      - PostgresContainer
    networks:
      - smartbus-net

  # Feedback service (dev)
  feedback-dev:
    container_name: smartbus-dev-Feedback
    build:
      context: ./Feedback
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgresContainer:5432/FeedbackDBDev
    ports:
      - "5003:5003"
    depends_on:
      - PostgresContainer
    networks:
      - smartbus-net

  # GTFS service (dev)
  gtfs:
    container_name: smartbus-dev-GTFS
    build:
      context: ./GTFS
      dockerfile: Dockerfile
    volumes:
      - ./GTFS/dev/public:/app/GtfsScript/public # Mounting public folder for GTFS data
      - type: bind
        source: ./GTFS/dev/config.yaml
        target: /app/GtfsScript/config/config.yaml
    depends_on:
      - PostgresContainer
    environment:
      - POSTGRES_URL=jdbc:postgresql://PostgresContainer:5432/GTFSDev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12683579
    ports:
      - "8000:8000"
    networks:
      - smartbus-net

  # OrderBus service (dev)
  orderbus-dev:
    container_name: smartbus-dev-OrderBus
    build:
      context: ./OrderBus
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgresContainer:5432/GTFSDev
    ports:
      - "6936:6936"
    depends_on:
      - PostgresContainer
      - gtfs
      - routes-dev
      - RedisContainer
    networks:
      - smartbus-net

  # Routes service (dev)
  routes-dev:
    container_name: smartbus-dev-Routes
    build:
      context: ./Routes
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "6924:6924"
    networks:
      - smartbus-net

  # Redis container (development)
  RedisContainer:
    container_name: smartbus-dev-RedisContainer
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data-dev:/data
    networks:
      - smartbus-net

  # Nginx service for development
  nginx:
    container_name: smartbus-dev-nginx
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf:ro  # Mount as read-only
    depends_on:
      - auth-dev
      - feedback-dev
      - orderbus-dev
      - routes-dev
    networks:
      - smartbus-net

# Define the network
networks:
  smartbus-net:
    driver: bridge

volumes:
  postgres-data-dev:
  redis-data-dev:
