version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: Ss123456
      POSTGRES_USER: postgres
      POSTGRES_DB: OrderBusDB
    ports:
      - "5432:5432"

  init_db:
    build:
      context: ./OrderBus/init_db
      args:
        GIT_REPO_URL: 'https://github.com/tamir303/GtfsScript.git'
    environment:
      POSTGRES_DB: OrderBusDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ss123456
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db

  app:
    build:
      context: ./OrderBus
    ports:
      - "10093:10093"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/OrderBusDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Ss123456
      SPRING_PROFILES_ACTIVE: default,generate-messages
    depends_on:
      - db
      - init_db
    links:
      - db