# PostgresSQL Configuration

database: GTFSDev # DB name, relatively matched to the configurations of OrderBus service
user: postgres # Username for registering the Postgres server
password: 12683579 # Password of the user
host: smartbus-dev-PostgresContainer # Relatively matched to the container's name of the Postgres service
port: 5432 # The regular port of the Postgres DB server